// Model-name archive. Detailed specifications are added only after research.
window.archiveCatalog={
"Abarth":"124 Spider|500|500C|595|595 Competizione|695|Grande Punto|Punto Evo|Ritmo 125 TC|Ritmo 130 TC",
"AC":"Ace|Aceca|Cobra|Greyhound|3000ME|Brooklands Ace|MK VI|378 GT Zagato|Cobra GT Roadster",
"Acura":"CL|CSX|EL|ILX|Integra|Legend|MDX|NSX|RDX|RL|RLX|RSX|SLX|TL|TLX|TSX|Vigor|ZDX",
"Alfa Romeo":"4C|6C|8C Competizione|145|146|147|155|156|159|164|166|Alfetta|Brera|Giulietta|GTV|MiTo|Montreal|Spider|Stelvio|Tonale",
"Alpine":"A106|A108|A110|A310|A610|GTA|A110 GT|A110 S|A110 R|A290",
"AMC":"AMX|Concord|Eagle|Gremlin|Hornet|Javelin|Matador|Pacer|Rambler American|Rebel|Spirit|Ambassador",
"Ariel":"Atom|Atom 2|Atom 3|Atom 4|Nomad|Nomad 2|Hipercar",
"Aston Martin":"DB1|DB2|DB4|DB5|DB6|DB7|DB9|DB11|DBS|DBX|Lagonda|One-77|Rapide|V8 Vantage|Vanquish|Virage|Vulcan|Victor|Valour",
"Audi":"50|80|90|100|200|A1|A2|A3|A4|A5|A6|A7|A8|Allroad|Coupe Quattro|e-tron GT|Q2|Q3|Q4 e-tron|Q5|Q7|Q8|Quattro|R8|RS 3|RS 4|RS 5|RS 6|RS 7|S1|S2|S3|S4|S5|S6|S7|S8|TT",
"Austin":"A30|A35|A40|A50|A55|A60|A90|A95|A99|A110|Allegro|Ambassador|Cambridge|Maestro|Maxi|Metro|Mini|Montego|Princess|Seven",
"BAC":"Mono|Mono R|Mono Turbo",
"Bentley":"3 Litre|4½ Litre|6½ Litre|8 Litre|Azure|Bentayga|Brooklands|Continental GT|Flying Spur|Mulsanne|S1|S2|S3|Turbo R|Arnage|Bacalar|Batur",
"BMW":"2002|3.0 CSL|1 Series|2 Series|3 Series|4 Series|5 Series|6 Series|7 Series|8 Series|i3|i4|i5|i7|i8|iX|M1|M2|M3|M4|M5|M6|M8|X1|X2|X3|X4|X5|X6|X7|XM|Z1|Z3|Z4|Z8",
"Bristol":"400|401|402|403|404|405|406|407|408|409|410|411|412|603|Beaufighter|Blenheim|Fighter|Bullet",
"Bugatti":"Type 13|Type 35|Type 41 Royale|Type 44|Type 46|Type 50|Type 55|Type 57|EB110|Veyron|Chiron|Divo|Centodieci|La Voiture Noire|Bolide|Mistral|Tourbillon",
"Buick":"Cascada|Century|Electra|Enclave|Encore|Envision|Estate Wagon|Gran Sport|LaCrosse|LeSabre|Lucerne|Park Avenue|Reatta|Regal|Riviera|Roadmaster|Skylark|Special|Verano|Wildcat",
"Cadillac":"Allanté|ATS|Brougham|Catera|Celestiq|Cimarron|CT4|CT5|CT6|CTS|DeVille|DTS|Eldorado|Escalade|Fleetwood|Lyriq|Seville|SRX|STS|XLR|XT4|XT5|XT6|XTS",
"Caterham":"Seven 160|Seven 170|Seven 270|Seven 310|Seven 360|Seven 420|Seven 485|Seven 620|Super Seven 600|Super Seven 2000|Project V",
"Chevrolet":"Astro|Avalanche|Aveo|Bel Air|Beretta|Blazer|Bolt|Camaro|Caprice|Cavalier|Chevelle|Chevette|Cobalt|Colorado|Corvair|Corvette|Cruze|El Camino|Equinox|Impala|Malibu|Monte Carlo|Nova|S-10|Silverado|Sonic|Spark|Suburban|Tahoe|Trailblazer|Traverse|Trax|Vega|Volt",
"Chrysler":"200|300|300M|Aspen|Cirrus|Concorde|Crossfire|Fifth Avenue|Imperial|LeBaron|LHS|New Yorker|Pacifica|Prowler|PT Cruiser|Sebring|Town & Country|Voyager",
"Citroën":"2CV|Ami|AX|BX|C1|C2|C3|C4|C5|C6|C8|CX|DS|Dyane|ë-C4|GS|Méhari|Saxo|SM|Traction Avant|Visa|Xantia|XM|Xsara",
"Dacia":"1300|1310|Duster|Jogger|Lodgy|Logan|Nova|Sandero|Solenza|Spring|SuperNova",
"De Tomaso":"Vallelunga|Mangusta|Pantera|Deauville|Longchamp|Guarà|Biguà|P72|P900",
"Dodge":"Avenger|Caliber|Caravan|Challenger|Charger|Colt|Coronet|Dart|Daytona|Diplomat|Durango|Hornet|Intrepid|Journey|Magnum|Monaco|Neon|Nitro|Omni|Ramcharger|Stealth|Stratus|Viper",
"Ferrari":"125 S|166 Inter|250 GT|275 GTB|288 GTO|308|328|348|360|365 GTB/4|400|412|456|458 Italia|488 GTB|512 BB|550 Maranello|575M|599 GTB|612 Scaglietti|812 Superfast|California|Daytona SP3|Dino 246 GT|Enzo|F8 Tributo|F12berlinetta|F40|F50|FF|GTC4Lusso|LaFerrari|Mondial|Portofino|Purosangue|Roma|SF90 Stradale|Testarossa",
"Fiat":"124 Spider|126|127|128|130|131|500|600|850|Barchetta|Brava|Bravo|Cinquecento|Coupé|Croma|Dino|Doblo|Multipla|Panda|Punto|Regata|Ritmo|Seicento|Stilo|Strada|Tempra|Tipo|Uno|X1/9",
"Ford":"Anglia|Bronco|Capri|Cortina|Cougar|Crown Victoria|Ecosport|Edge|Escape|Escort|Everest|Expedition|Explorer|F-150|Fairlane|Falcon|Fiesta|Flex|Focus|Fusion|Galaxie|GT|Ka|Kuga|LTD|Maverick|Mondeo|Mustang|Pinto|Probe|Puma|Ranger|Sierra|Taurus|Thunderbird|Torino|Transit",
"Genesis":"G70|G80|G90|GV60|GV70|GV80|GV80 Coupe",
"GMC":"Acadia|Canyon|Envoy|Hummer EV|Jimmy|Safari|Savana|Sierra|Sonoma|Suburban|Syclone|Terrain|Typhoon|Vandura|Yukon",
"Honda":"Accord|Beat|Brio|Civic|Clarity|Concerto|CR-V|CR-X|CR-Z|Crosstour|Element|Fit|HR-V|Insight|Integra|Jazz|Legend|N-Box|NSX|Odyssey|Passport|Pilot|Prelude|Ridgeline|S2000|S500|S600|S660|Stream",
"Hyundai":"Accent|Azera|Elantra|Equus|Excel|Genesis Coupe|Getz|Grandeur|i10|i20|i30|Ioniq|Ioniq 5|Ioniq 6|Kona|Nexo|Palisade|Pony|Santa Cruz|Santa Fe|Sonata|Staria|Tiburon|Tucson|Veloster|Venue",
"Infiniti":"EX|FX|G20|G35|G37|I30|I35|J30|JX|M30|M35|M45|Q30|Q40|Q45|Q50|Q60|Q70|QX30|QX50|QX55|QX60|QX70|QX80",
"Isuzu":"Amigo|Ascender|Axiom|D-Max|Faster|Gemini|Hombre|Impulse|i-Series|MU|Oasis|Piazza|Rodeo|Trooper|VehiCROSS",
"Jaguar":"C-Type|D-Type|E-Type|F-Pace|F-Type|I-Pace|Mark 2|S-Type|X-Type|XE|XF|XJ|XJ-S|XJ220|XK|XK120|XK140|XK150|XK8",
"Jeep":"Cherokee|CJ|Commander|Compass|Gladiator|Grand Cherokee|Grand Wagoneer|Liberty|Patriot|Renegade|Wagoneer|Wagoneer S|Willys MB|Wrangler",
"Kia":"Amanti|Borrego|Cadenza|Carnival|Ceed|Cerato|EV3|EV5|EV6|EV9|Forte|K5|K900|Niro|Optima|Picanto|Rio|Rondo|Sedona|Seltos|Sorento|Soul|Sportage|Stinger|Telluride",
"Koenigsegg":"CC8S|CCR|CCX|CCXR|Agera|Agera R|Agera RS|One:1|Regera|Jesko|Gemera|CC850",
"Lamborghini":"350 GT|400 GT|Aventador|Countach|Diablo|Espada|Gallardo|Huracán|Islero|Jalpa|Jarama|LM002|Miura|Murciélago|Reventón|Revuelto|Silhouette|Urraco|Urus|Veneno|Sesto Elemento|Sián",
"Lancia":"Appia|Aurelia|Beta|Dedra|Delta|Flaminia|Flavia|Fulvia|Gamma|Kappa|Lambda|Lybra|Montecarlo|Musa|Phedra|Prisma|Stratos|Thema|Thesis|Ypsilon",
"Lexus":"CT|ES|GS|GX|HS|IS|LC|LFA|LM|LS|LX|NX|RC|RX|RZ|SC|TX|UX",
"Lotus":"2-Eleven|3-Eleven|Elan|Eletre|Elise|Elite|Emeya|Emira|Esprit|Europa|Evija|Evora|Excel|Exige|Seven",
"Maserati":"3200 GT|3500 GT|Biturbo|Bora|Coupe|Ghibli|GranCabrio|GranSport|GranTurismo|Grecale|Indy|Khamsin|Levante|MC12|MC20|Merak|Quattroporte|Shamal|Spyder",
"Mazda":"121|2|3|5|6|323|626|929|B-Series|Bongo|Carol|Cosmo|CX-3|CX-30|CX-5|CX-50|CX-60|CX-7|CX-70|CX-8|CX-9|CX-90|Demio|Familia|Millenia|MPV|MX-3|MX-5|MX-6|Protegé|R100|RX-2|RX-3|RX-4|RX-7|RX-8|Tribute",
"McLaren":"12C|540C|570S|600LT|620R|650S|675LT|720S|750S|765LT|Artura|Elva|F1|GT|GTS|MP4-12C|P1|Sabre|Senna|Solus GT|Speedtail|W1",
"Mercedes-Benz":"190E|220|230|300 SL|A-Class|B-Class|C-Class|CLA|CLE|CLK|CLS|E-Class|EQA|EQB|EQC|EQE|EQS|G-Class|GLA|GLB|GLC|GLE|GLK|GLS|M-Class|R-Class|S-Class|SL|SLC|SLK|SLR McLaren|SLS AMG|V-Class|X-Class",
"MG":"3|4 EV|5 EV|6|A|B|C|F|GT|HS|Maestro|Metro|Midget|Montego|RV8|TF|XPower SV|ZS|ZT",
"Mini":"Classic Mini|Clubman|Convertible|Cooper|Countryman|Coupe|Paceman|Roadster|Aceman",
"Mitsubishi":"3000GT|Airtrek|Carisma|Challenger|Colt|Cordia|Delica|Diamante|Eclipse|Eclipse Cross|Endeavor|FTO|Galant|i-MiEV|Lancer|Magna|Mirage|Montero|Outlander|Pajero|Raider|RVR|Sigma|Starion|Triton",
"Nissan":"200SX|240SX|280ZX|300ZX|350Z|370Z|Almera|Altima|Ariya|Armada|Bluebird|Cedric|Cube|Figaro|Frontier|Gloria|GT-R|Juke|Kicks|Laurel|Leaf|March|Maxima|Micra|Murano|Navara|Note|Pathfinder|Patrol|Primera|Pulsar|Qashqai|Quest|Rogue|Sentra|Silvia|Skyline|Stagea|Stanza|Sunny|Terrano|Titan|Versa|X-Trail|Xterra|Z",
"Opel":"Adam|Admiral|Agila|Ampera|Antara|Astra|Calibra|Cascada|Combo|Commodore|Corsa|Crossland|Diplomat|Frontera|GT|Insignia|Kadett|Manta|Meriva|Mokka|Monza|Omega|Rekord|Senator|Speedster|Tigra|Vectra|Zafira",
"Pagani":"Zonda C12|Zonda S|Zonda F|Zonda Cinque|Zonda R|Huayra|Huayra BC|Huayra Roadster|Imola|Codalunga|Utopia",
"Peugeot":"104|106|107|108|204|205|206|207|208|304|305|306|307|308|309|404|405|406|407|408|504|505|508|604|605|607|1007|2008|3008|4007|5008|RCZ",
"Pontiac":"6000|Aztek|Bonneville|Catalina|Fiero|Firebird|G5|G6|G8|Grand Am|Grand Prix|GTO|LeMans|Montana|Parisienne|Phoenix|Solstice|Sunbird|Sunfire|Tempest|Torrent|Trans Sport|Vibe",
"Porsche":"356|550 Spyder|718 Boxster|718 Cayman|911|912|914|918 Spyder|924|928|944|959|968|Boxster|Carrera GT|Cayenne|Cayman|Macan|Panamera|Taycan",
"Renault":"4|5|6|8|9|10|11|12|14|16|17|18|19|20|21|25|Avantime|Captur|Clio|Dauphine|Espace|Fluence|Fuego|Kadjar|Kangoo|Koleos|Laguna|Mégane|Modus|Rafale|Safrane|Scénic|Talisman|Twingo|Zoe",
"Rolls-Royce":"10 hp|20 hp|20/25|25/30|Camargue|Corniche|Cullinan|Dawn|Ghost|Park Ward|Phantom|Silver Cloud|Silver Dawn|Silver Seraph|Silver Shadow|Silver Spirit|Silver Spur|Silver Wraith|Spectre|Wraith",
"Saab":"9-2X|9-3|9-4X|9-5|9-7X|90|92|93|95|96|99|900|9000|Sonett",
"SEAT":"Alhambra|Altea|Arona|Arosa|Ateca|Cordoba|Exeo|Ibiza|Inca|Leon|Malaga|Marbella|Mii|Ronda|Tarraco|Toledo",
"Subaru":"360|Alcyone|Ascent|Baja|BRAT|BRZ|Crosstrek|Exiga|Forester|Impreza|Justy|Legacy|Leone|Levorg|Loyale|Outback|SVX|Tribeca|Vivio|WRX|XT",
"Suzuki":"Across|Alto|Baleno|Cappuccino|Celerio|Equator|Escudo|Esteem|Forenza|Fronte|Grand Vitara|Ignis|Jimny|Kizashi|Liana|Samurai|Sidekick|Splash|Swift|SX4|Vitara|Wagon R|X-90|XL7",
"Toyota":"2000GT|4Runner|86|Alphard|Avalon|Avensis|Aygo|bB|C-HR|Camry|Carina|Celica|Century|Corolla|Corona|Cressida|Crown|FJ Cruiser|Fortuner|GR86|HiAce|Highlander|Hilux|Land Cruiser|MR2|Paseo|Previa|Prius|RAV4|Sequoia|Sera|Soarer|Starlet|Supra|Tacoma|Tercel|Tundra|Venza|Yaris",
"Volkswagen":"Amarok|Arteon|Atlas|Beetle|Bora|Caddy|CC|Corrado|Eos|Fox|Golf|ID.3|ID.4|ID.5|ID.6|ID.7|ID. Buzz|Jetta|Karmann Ghia|Lupo|Multivan|Passat|Phaeton|Polo|Rabbit|Scirocco|Sharan|Taos|T-Cross|Tiguan|Touareg|Touran|Transporter|Up!|Vento",
"Volvo":"140|164|240|260|340|360|440|460|480|740|760|780|850|940|960|C30|C40|C70|EX30|EX40|EX90|P1800|S40|S60|S70|S80|S90|V40|V50|V60|V70|V90|XC40|XC60|XC70|XC90",
"BYD":"Atto 3|Dolphin|Dolphin Surf|Han|Seal|Seal U|Seagull|Song Plus|Tang|Qin|Qin Plus|Yuan Plus|e6|F0|F3|F6|G3|G6|L3|M6|S6|S8",
"Chery":"A1|A3|A5|Amulet|Arrizo 3|Arrizo 5|Arrizo 7|Arrizo 8|CrossEastar|E5|Eastar|Exeed TX|Fulwin|QQ|Tiggo|Tiggo 2|Tiggo 3|Tiggo 4|Tiggo 5|Tiggo 7|Tiggo 8",
"Cupra":"Ateca|Born|Formentor|Leon|Tavascan|Terramar|Raval",
"Daihatsu":"Applause|Atrai|Charade|Copen|Cuore|Feroza|Gran Max|Hijet|Materia|Mira|Move|Rocky|Sirion|Taft|Tanto|Terios|YRV",
"Daewoo":"Cielo|Espero|Evanda|Kalos|Korando|Lacetti|Lanos|Leganza|LeMans|Magnus|Matiz|Musso|Nexia|Nubira|Racer|Tacuma|Tico",
"Geely":"Atlas|Azkarra|Binrui|Binyue|Boyue|Coolray|Emgrand|Emgrand EC7|Geometry A|Geometry C|Galaxy E5|Galaxy L7|GC9|Haoyue|Icon|Monjaro|Okavango|Panda|Preface|Tugella",
"Holden":"Adventra|Astra|Barina|Calais|Camira|Caprice|Colorado|Commodore|Cruze|Gemini|Jackaroo|Kingswood|Monaro|Rodeo|Sandman|Statesman|Torana|Ute|Vectra",
"Hongqi":"E-HS9|E-QM5|H5|H6|H7|H9|HS3|HS5|HS7|L5|LS7|S9",
"Hummer":"H1|H2|H3|H3T|EV Pickup|EV SUV",
"Lada":"1200|1300|1500|2101|2105|2107|Granta|Kalina|Largus|Niva|Oka|Priora|Samara|Vesta|XRAY",
"Lucid":"Air|Air Pure|Air Touring|Air Grand Touring|Air Dream Edition|Air Sapphire|Gravity",
"Mahindra":"Alturas G4|Armada|Bolero|KUV100|Marazzo|NuvoSport|Quanto|Roxor|Scorpio|Scorpio N|Thar|Verito|XUV300|XUV400|XUV500|XUV700|Xylo",
"Maruti Suzuki":"800|1000|A-Star|Alto|Baleno|Brezza|Celerio|Ciaz|Dzire|Eeco|Ertiga|Esteem|Fronx|Grand Vitara|Gypsy|Ignis|Jimny|Kizashi|Omni|S-Presso|Swift|Wagon R|Zen",
"Mercury":"Capri|Comet|Cougar|Grand Marquis|Marauder|Mariner|Marquis|Milan|Montego|Monterey|Mountaineer|Mystique|Sable|Topaz|Tracer|Villager|Zephyr",
"Nio":"EC6|EC7|EL6|EL7|EL8|EP9|ES6|ES7|ES8|ET5|ET5 Touring|ET7|ET9|Firefly|Onvo L60",
"Oldsmobile":"Achieva|Alero|Aurora|Bravada|Cutlass|Eighty-Eight|Firenza|Intrigue|Ninety-Eight|Omega|Silhouette|Starfire|Toronado|Vista Cruiser",
"Perodua":"Alza|Aruz|Ativa|Axia|Bezza|Kelisa|Kenari|Kembara|Kancil|Myvi|Nautica|Rusa|Viva",
"Plymouth":"Acclaim|Barracuda|Belvedere|Breeze|Caravelle|Colt|Duster|Fury|Gran Fury|Horizon|Laser|Neon|Prowler|Reliant|Road Runner|Satellite|Sundance|Valiant|Volare|Voyager",
"Polestar":"1|2|3|4|5|6|Precept",
"Proton":"Arena|Exora|Gen-2|Inspira|Iriz|Juara|Perdana|Persona|Prevé|Putra|Saga|Satria|Savvy|Suprima S|Tiara|Waja|Wira|X50|X70|X90",
"RAM":"1500|1500 Classic|1500 REV|1500 Ramcharger|2500|3500|4500|5500|Dakota|ProMaster|ProMaster City|Rampage",
"Rivian":"R1T|R1S|R2|R3|R3X|EDV|Commercial Van",
"Rover":"200|400|600|800|CityRover|Maestro|Metro|Mini|Montego|P3|P4|P5|P6|SD1|Streetwise|75",
"Saturn":"Aura|Astra|Ion|L-Series|Outlook|Relay|S-Series|Sky|Vue",
"Scion":"FR-S|iA|iM|iQ|tC|xA|xB|xD",
"Škoda":"100|105|120|130|Citigo|Elroq|Enyaq|Fabia|Favorit|Felicia|Forman|Kamiq|Karoq|Kodiaq|Octavia|Rapid|Roomster|Scala|Slavia|Superb|Yeti",
"SsangYong":"Actyon|Chairman|Istana|Korando|Kyron|Musso|Rexton|Rodius|Stavic|Tivoli|Torres|XLV",
"Tata":"Altroz|Aria|Bolt|Curvv|Harrier|Hexa|Indica|Indigo|Manza|Nano|Nexon|Punch|Safari|Sierra|Sumo|Tiago|Tigor|Vista|Zest",
"Vauxhall":"Adam|Agila|Ampera|Astra|Calibra|Carlton|Cavalier|Chevette|Corsa|Cresta|Frontera|Insignia|Meriva|Mokka|Monaro|Nova|Omega|Signum|Tigra|Vectra|Victor|Viva|VX220|Zafira",
"VinFast":"Fadil|Lux A2.0|Lux SA2.0|President|VF 3|VF 5|VF 6|VF 7|VF 8|VF 9|Minio Green",
"Wartburg":"311|312|313|353|1.3",
"Wuling":"Air EV|Almaz|Binguo EV|Cortez|Formo|Hongguang|Hongguang Mini EV|Journey|Mini EV|Rongguang|Starlight|Sunshine|Victory|Xingchi|Xingyun",
"XPeng":"G3|G6|G9|P5|P7|P7i|P7+|X9|Mona M03",
"Zeekr":"001|001 FR|007|009|7X|MIX|X",
"ZIL":"101|110|111|114|115|117|118|4104|41041",
"Zastava":"10|101|128|1300|1500|750|Florida|Koral|Skala|Yugo"
};
